name: Install Terraform on EC2

on:
  push:
    branches:
      - two
  
  
jobs:
  install_terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Connect to EC2 and install Terraform
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.USER_NAME }}
          key: ${{ secrets.KEY_FILE }}

          script: |
            echo "Connected to EC2"

            echo "Adding HashiCorp repository..."
            sudo cp /home/ec2-user/main.html /usr/share/nginx/html/
