name: Install Terraform on EC2

on:
  push:
    branches:
      - main
  
  
jobs:
  install_terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Connect to EC2 and install Terraform
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.USER_NAME }}
          key: ${{ secrets.KEY_FILE }}

          script: |
            echo "Connected to EC2"

            echo "Installing utilities..."
            sudo dnf update -y

            echo "update nginx"
            sudo dnf install nginx -y

            
            
